### PR TITLE
HSA: Add memory pools API

### LINKED ISSUE #210: `mapreducedim!` failing in multi-AMDGPU configuration
The following operation `all(A .== B)` where `A` and `B` are `ROCArray`s fails when executed on multiple AMDGPUs (with MPI). All seems to work fine when using a single GPU (although the operation being slow - ~10sec for a 10 elems ROCVector).

Executing the following code with `mpirun -np 2 julia reproducer.jl` fails with reported stacktrace when launched on 2 Vega 20 WKS GL-XE [Radeon Pro VII] (gfx906) GPUs.

- Reproducer:
```
using MPI
using AMDGPU
MPI.Init()
comm = MPI.COMM_WORLD
rank = MPI.Comm_rank(comm)
# select device
comm_l = MPI.Comm_split_type(comm, MPI.MPI_COMM_TYPE_SHARED, rank)
rank_l = MPI.Comm_rank(comm_l)
gpu_id = AMDGPU.device!(rank_l+1)
my_gpu = AMDGPU.device()
println("rank=$rank_l (gpu_id=$my_gpu)")
MPI.Barrier(comm)
A = rand(6,1)
B = copy(A)
B[[1, end]] .= 0.0
@show A = ROCArray(A)
@show B = ROCArray(B)
@show !all(A .== B)
MPI.Finalize()
```

- Stacktrace:
```
[lraess@ault dev]$ mpirun -np 2 julia reproducer.jl
rank=0 (gpu_id=1)
rank=1 (gpu_id=2)
A = ROCArray(A) = [0.4113430371388549; 0.48951690445617935; 0.6913549630475396; 0.10297031576130089; 0.8814779119079794; 0.18849311453373707;;]
B = ROCArray(B) = [0.0; 0.48951690445617935; 0.6913549630475396; 0.10297031576130089; 0.8814779119079794; 0.0;;]
A = ROCArray(A) = [0.7568648336025494; 0.30752100365629875; 0.20437756202583046; 0.3408972045571961; 0.8616001299312898; 0.18197018060074066;;]
B = ROCArray(B) = [0.0; 0.30752100365629875; 0.20437756202583046; 0.3408972045571961; 0.8616001299312898; 0.0;;]
ERROR: LoadError: BoundsError: attempt to access 0-element Vector{AMDGPU.HSA.LibHSARuntime.hsa_region_s} at index [1]
Stacktrace:
 [1] getindex
   @ ./array.jl:861 [inlined]
 [2] first
   @ ./abstractarray.jl:398 [inlined]
 [3] mapreducedim!(f::typeof(identity), op::typeof(&), R::ROCMatrix{Bool}, A::Base.Broadcast.Broadcasted{AMDGPU.ROCArrayStyle{2}, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}, typeof(identity), Tuple{ROCMatrix{Bool}}}; init::Bool)
   @ AMDGPU ~/.julia/packages/AMDGPU/Id9fa/src/mapreduce.jl:134
 [4] #_mapreduce#22
   @ ~/.julia/packages/GPUArrays/VNhDf/src/host/mapreduce.jl:65 [inlined]
 [5] #mapreduce#20
   @ ~/.julia/packages/GPUArrays/VNhDf/src/host/mapreduce.jl:31 [inlined]
 [6] mapreduce
   @ ~/.julia/packages/GPUArrays/VNhDf/src/host/mapreduce.jl:31 [inlined]
 [7] all(A::ROCMatrix{Bool})
   @ GPUArrays ~/.julia/packages/GPUArrays/VNhDf/src/host/mapreduce.jl:75
 [8] top-level scope
   @ show.jl:1047
in expression starting at /scratch/lraess/dev/device_select.jl:18
!(all(A .== B)) = true
```

### PR DESCRIPTION
**Pull request by jpsamaroo**
Adds support for HSA's memory pools API, which works around the bug reported in https://github.com/RadeonOpenCompute/ROCR-Runtime/issues/134. We still use HSA's regions API for finegrained and kernarg allocations, because those aren't exposed via this API.

Also fixes #210 

Todo:
- [x] Add allocation API for arbitrary regions/memory pools
- [x] Add tests for regions and memory pools queries
- [x] Add multi-GPU test for coarsegrained allocations
- [x] Add basic docs

### CODE REVIEW

File: src/agent.jl [hunk 1]
```diff
@@ -274,38 +215,248 @@ end
...
+struct HSAMemoryPool
+    pool::HSA.AMDMemoryPool
+end
+
+function iterate_pools_cb(pool::HSA.AMDMemoryPool, pools)
+    push!(pools, pool)
+    return HSA.STATUS_SUCCESS
+end
+
+function memory_pools(agent::HSAAgent)
```
Comment (vchuravy) [inline src/agent.jl:356]: Can we memoize this? Maybe steal the code from CUDA?

cc: @maleadt
